name: computing-in-context
channels:
  - conda-forge
dependencies:
  - python=3.9  # Ensure the Python version is specified
  - jupyter-book>=0.12.0  # Specify minimum version
  - sphinx>=6.2.0
  - myst-parser  # Required for parsing Markdown files
  - sphinx-rtd-theme  # Common theme for Read the Docs
  